create table provider
(
    id      int primary key 
            generated by default as identity,
    name    text,
    phone   text
);

create table transport
(
    id          int primary key 
                generated by default as identity,
    provider_id int references provider,
    model       text,
    volume      float,
    number      int
);

insert into provider(name, phone) values
('Северный ветер', '9535004378'),
('Южный мяч', '9545003267'),
('Красная кнопка', '9645439023');

insert into transport(provider_id, model, volume, number) values
(1, 'Машина', 23.1, 123),
(1, 'Самолет', 12, 124),
(2, 'Вертолет', 10.1, 125),
(2, 'Катер', 56, 126);

select 
    pr.id as provider_id,
    pr.name,
    pr.phone,
    coalesce(jsonb_agg(jsonb_build_object(
        'id', tr.id, 'model', tr.model, 'volume', tr.volume, 'number', tr.number))
            filter (where tr.id is not null), '[]') as transport
from provider pr
left join transport tr on pr.id = tr.provider_id
group by pr.id