create table provider
(
    id      int primary key 
            generated by default as identity,
    name    text,
    phone   text
);

create table transport
(
    id          int primary key 
                generated by default as identity,
    provider_id int references provider,
    stamp       text,
    model       text,
    capacity    float
);

insert into provider(name, phone) values
('Северный ветер', '9535004378'),
('Южный мяч', '9545003267'),
('Красная кнопка', '9645439023');

insert into transport(provider_id, stamp, model, capacity) values
(1, 'Toyota', 'Легковой', 123),
(1, 'Chevrolet', 'Легковой', 120),
(2, 'Lada', 'Грузовик', 58),
(2, 'Lada', 'Легковой', 60);
    
select 
    pr.id as provider_id,
    pr.name,
    pr.phone,
    coalesce(jsonb_agg(jsonb_build_object(
        'id', tr.id, 'model', tr.model, 'stamp', tr.stamp, 'capacity', tr.capacity))
            filter (where tr.id is not null), '[]') as transport
from provider pr
left join transport tr on pr.id = tr.provider_id
group by pr.id