create table festival
(
    id              int primary key 
                    generated by default as identity,
    name            text,
    date            date,
    place           text
);

create table performance
(
    id          int primary key 
                generated by default as identity,
    festival_id int references festival,
    name        text,
    date        date,
    genre       text
);

insert into festival(name, date, place) values
('Фестиваль национальной кухни', '2024-05-20', 'Вологда'),
('Фестиваль необычных костюмов', '2024-12-10', 'Москва'),
('Фестиваль новейших технологий', '2024-03-15', 'Санкт-Петербург');

insert into performance(festival_id, name, date, genre) values
(1, 'Выступление лучших шеф-поваров', '2024-05-21', 'Приготовление еды'),
(1, 'Выступление помощников шеф-поваров', '2024-05-22', 'Приготовление еды'),
(2, 'Модный показ', '2024-12-11', 'Показ одежды'),
(2, 'Мастер-класс по изготовлению костюмов', '2024-12-12', 'Показ одежды');

select
    f.id as festival_id,
    f.name,
    f.date,
    f.place,
    coalesce(jsonb_agg(json_build_object(
        'id', p.id, 'name', p.name, 'date', p.date, 'genre', p.genre))
            filter (where p.id is not null), '[]') as performance
from festival f
left join performance p on f.id = p.festival_id
group by f.id